# Generated by Django 4.0.3 on 2022-05-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tickersymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(choices=[('aapl', 'AAPL'), ('msft', 'MSFT'), ('goog', 'GOOG'), ('googl', 'GOOGL'), ('amzn', 'AMZN'), ('tsla', 'TSLA')], default='aapl', max_length=6)),
            ],
        ),
    ]
