# Generated by Django 4.0.3 on 2022-04-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='number_of_questions',
        ),
    ]
